 ## Data Inspection & Missing Value Imputation

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\ankit\Downloads\messy_customer_sales_data.csv")

In [3]:
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10195,CUST10767,Robert Lewis,female,35.0 years,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10196,NaN,Diane Evans,M,53.0,bangalore,2023-12-31,2025-05-07,11639.0,7.0,lisadennis@example.net,5200349941,IND
10197,CUST6315,Joshua Martinez,m,25.0,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55.0,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34.0,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                10200 non-null  object
 2   Gender              9174 non-null   object
 3   Age                 9249 non-null   object
 4   City                9184 non-null   object
 5   Signup_Date         10200 non-null  object
 6   Last_Purchase_Date  9188 non-null   object
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  object
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 956.4+ KB

In [5]:
df.describe().round()

       Purchase_Amount  Feedback_Score  Phone_Number
count           9179.0          9177.0  1.020000e+04
mean           29090.0             5.0  4.979974e+09
std           208697.0             3.0  2.902593e+09
min             -500.0             1.0  9.208990e+05
25%            12295.0             3.0  2.449157e+09
50%            24330.0             5.0  4.988639e+09
75%            37130.0             8.0  7.510448e+09
max          9999999.0            10.0  9.994402e+09

In [6]:
df.shape

(10200, 12)

In [7]:
(df.isnull().sum()/len(df)*100).round(2)

Customer_ID           10.03
Name                   0.00
Gender                10.06
Age                    9.32
City                   9.96
Signup_Date            0.00
Last_Purchase_Date     9.92
Purchase_Amount       10.01
Feedback_Score        10.03
Email                  0.00
Phone_Number           0.00
Country                7.18
dtype: float64

In [8]:
df[df.duplicated()].shape

(15, 12)

In [9]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [10]:
df['Customer_ID'].value_counts().head(10)

CUST3374     2
CUST7749     2
CUST10800    2
CUST6588     2
CUST9062     2
CUST5472     2
CUST1852     2
CUST4160     2
CUST5019     2
CUST6288     2
Name: Customer_ID, dtype: int64

In [11]:
df[df['Customer_ID']=='CUST3374']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2914,CUST3374,Timothy Wallace,m,58.0,Bangalore,2024-03-08,2025-08-21,45779.0,1.0,glenn95@example.org,9687701793,India
3047,CUST3374,Timothy Wallace,m,58.0,bangalore,2024-03-08,2025-08-21,45779.0,1.0,glenn95@example.org,9687701793,India

In [12]:
for col in df.columns:
    if df[col].nunique()<20:
        print (df[col].value_counts())
        print('-'*50)

f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: Gender, dtype: int64
--------------------------------------------------
 Kolkata       820
 Mumbai        812
 Chennai       784
 Bangalore     773
 Hyderabad     770
 Delhi         763
 CHENNAI       404
 KOLKATA       395
 MUMBAI        393
 hyderabad     384
 bangalore     383
 DELHI         378
 delhi         369
 BANGALORE     363
 HYDERABAD     360
 mumbai        352
 chennai       343
 kolkata       338
Name: City, dtype: int64
--------------------------------------------------
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: Feedback_Score, dtype: int64
--------------------------------------------------
India    7132
IND       793
india     772
InDia     771
Name: Country, dtype: int64
--------------------------------------------------

In [13]:
df.dropna(subset=['Customer_ID'],inplace=True)

In [14]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [15]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

In [16]:
df['Age'].unique()

array([ 52.,  nan,  62.,  40.,  41.,  18.,  26.,  32.,  22.,  59.,  65.,
        61.,  31.,  55.,  69.,  24.,  63.,  19.,  50.,  56.,  36.,  68.,
        43.,  38.,  27.,  23.,  25.,  66.,  28.,  30.,  46.,  48.,  20.,
        37.,  67.,  51.,  35.,  58.,  29.,  39.,  49.,  47.,  42.,  44.,
        64.,  53.,  60.,  45.,  21.,  34.,  54.,  33.,  57., 250.,   3.,
       -10.])

In [17]:
df['Age'].dtype

dtype('float64')

In [18]:
df['Age'] = df['Age'].fillna(df['Age'].median()).astype('int64')

In [19]:
df['Age'].unique()

array([ 52,  43,  62,  40,  41,  18,  26,  32,  22,  59,  65,  61,  31,
        55,  69,  24,  63,  19,  50,  56,  36,  68,  38,  27,  23,  25,
        66,  28,  30,  46,  48,  20,  37,  67,  51,  35,  58,  29,  39,
        49,  47,  42,  44,  64,  53,  60,  45,  21,  34,  54,  33,  57,
       250,   3, -10], dtype=int64)

In [20]:
df['Purchase_Amount'] = df['Purchase_Amount'].fillna(df['Purchase_Amount'].median())

In [21]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [22]:
df['Feedback_Score'] = df['Feedback_Score'].fillna(df['Feedback_Score'].mode()[0])

In [23]:
for col in ['Gender','City','Country']:
    df[col].fillna(df[col].mode()[0],inplace=True)

In [24]:
df['Last_Purchase_Date'].ffill(inplace=True)

In [25]:
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    0
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

# Text Normalization & Categorical Cleaning

In [26]:
df['Gender'].unique()

df['Gender'] = df['Gender'].str.lower().str.strip()
df['Gender'].replace({'m': 'male', 'f': 'female'}, inplace=True)
df['Gender'].unique()
df['City'] = df['City'].str.strip().str.lower()
df['Country'] = df['Country'].str.strip().str.lower()

In [27]:
df['Country'].replace({'ind': 'india'}, inplace=True)

In [28]:
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,male,52,kolkata,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,india
1,CUST5957,Jason Thomas,male,43,kolkata,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,female,62,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,india
3,CUST2934,Brenda Pierce,female,40,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,female,41,chennai,2024-04-05,2024-12-15,24268.0,8.0,denise84@example.org,2665569480,india
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,female,40,kolkata,2024-08-21,2024-10-26,35101.0,1.0,mitchellrivera@example.net,6380823112,india
10195,CUST10767,Robert Lewis,female,43,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,india
10197,CUST6315,Joshua Martinez,male,25,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,india
10198,CUST4812,Sarah Miller,female,55,kolkata,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,india
10199,CUST6588,David Potter,female,34,hyderabad,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,india

In [29]:
df[df.duplicated()].shape

(152, 12)

In [30]:
df.drop_duplicates(inplace=True)

In [31]:
df['Customer_ID'].value_counts()

CUST6069     2
CUST10852    2
CUST8033     2
CUST2510     2
CUST7439     2
            ..
CUST7130     1
CUST10857    1
CUST8117     1
CUST3141     1
CUST4812     1
Name: Customer_ID, Length: 9000, dtype: int64

In [32]:
df.drop_duplicates(subset=['Customer_ID'], keep = 'first',inplace=True)

In [33]:
df.shape

(9000, 12)

In [34]:
df.dtypes

Customer_ID            object
Name                   object
Gender                 object
Age                     int64
City                   object
Signup_Date            object
Last_Purchase_Date     object
Purchase_Amount       float64
Feedback_Score        float64
Email                  object
Phone_Number            int64
Country                object
dtype: object

In [35]:
df['Signup_Date'] = pd.to_datetime(df['Signup_Date'])
df['Last_Purchase_Date'] = pd.to_datetime(df['Last_Purchase_Date'])

# Handling Outliers (Age & Purchase Amount)

In [36]:
df.loc[(df['Age'] < 15) | (df['Age'] > 100), 'Age'] = None
df['Age'] = df['Age'].fillna(df['Age'].median()).astype(int)

In [37]:
df = df[df['Purchase_Amount'] > 0].copy()

Q1 = df['Purchase_Amount'].quantile(0.25)
Q3 = df['Purchase_Amount'].quantile(0.75)
IQR = Q3 - Q1
upper_limit = Q3 + 1.5 * IQR

df['Purchase_Amount'] = df['Purchase_Amount'].clip(upper=upper_limit)

# Logical Consistency Checks (Dates & Constraints)

In [38]:
invalid_dates = df[df['Last_Purchase_Date'] < df['Signup_Date']]
print(f"Invalid Date Records: {len(invalid_dates)}")

df = df[df['Last_Purchase_Date'] >= df['Signup_Date']]

Invalid Date Records: 913

# Exporting Cleaned Dataset

In [39]:
df.to_csv("cleaned_customer_sales_data.csv", index=False)